const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('nl-BE',{notation:n>=10000?'compact':'standard',maximumFractionDigits:1}).format(n||0),pct=n=>(n||0).toFixed(1)+'%',esc=s=>(s||'Zonder caption').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));function go(id){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id))}
const er=m=>m.reach?((m.likes+m.comments+m.shares+m.saved)/m.reach*100):0,words=s=>(s||'').toLowerCase().match(/#[\p{L}\d_]+/gu)||[];
async function load(){try{const r=await fetch('/.netlify/functions/social-data',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'API fout');$('status').classList.add('live');$('status').querySelector('span').textContent='Live • @'+d.account.username;
const sorted=[...d.media].sort((a,b)=>b.views-a.views),top=sorted.slice(0,3),low=[...sorted].reverse().filter(x=>x.views).slice(0,3),eng=d.totals.reach?(d.totals.likes+d.totals.comments+d.totals.shares+d.totals.saved)/d.totals.reach*100:0,score=Math.min(100,Math.round((d.totals.reach?d.totals.views/d.totals.reach:0)*24+eng*5));
Object.entries({views:d.totals.views,reach:d.totals.reach,likes:d.totals.likes,shares:d.totals.shares,saves:d.totals.saved,followers:d.account.followers_count,mediaCount:d.account.media_count}).forEach(([k,v])=>$(k).textContent=fmt(v));$('engagement').textContent=pct(eng);$('growScore').innerHTML=score+'<span>/100</span>';$('scoreNote').textContent=d.media.length+' recente posts geanalyseerd';$('accountName').textContent='@'+d.account.username;$('updated').textContent='Bijgewerkt '+new Date(d.updatedAt).toLocaleString('nl-BE');$('heroTitle').textContent='Beste post: '+fmt(top[0]?.views)+' views • '+pct(er(top[0]))+' engagement';$('heroText').textContent='Je dashboard vergelijkt nu views, bereik, likes, comments, shares, saves en engagement per post.';
const item=(m,i)=>'<div class="signal"><b>0'+(i+1)+'</b><span><strong>'+esc((m.caption||m.media_product_type).slice(0,52))+'</strong><small>'+fmt(m.views)+' views • '+fmt(m.shares)+' shares • '+pct(er(m))+' ER</small></span></div>';$('topContent').innerHTML=top.map(item).join('');
$('radarRows').innerHTML=sorted.map((m,i)=>'<tr onclick="window.open(\''+m.permalink+'\',\'_blank\')"><td>'+(i+1)+'</td><td>'+esc((m.caption||'Zonder caption').slice(0,52))+'</td><td>'+esc(m.media_product_type||m.media_type)+'</td><td>'+fmt(m.views)+'</td><td>'+fmt(m.reach)+'</td><td>'+fmt(m.likes)+'</td><td>'+fmt(m.shares)+'</td><td>'+fmt(m.saved)+'</td><td>'+pct(er(m))+'</td></tr>').join('');
$('winners').innerHTML=top.map(item).join('');$('laggards').innerHTML=low.map(item).join('');
const reels=d.media.filter(x=>x.media_product_type==='REELS'),others=d.media.filter(x=>x.media_product_type!=='REELS'),avg=a=>a.length?a.reduce((s,x)=>s+x.views,0)/a.length:0,bestType=avg(reels)>=avg(others)?'Reels':'niet-Reels';const shareRate=d.totals.views?d.totals.shares/d.totals.views*100:0;
$('growthActions').innerHTML='<article class="card"><b>01</b><h3>'+bestType+' leveren meer views</h3><p>Gemiddeld '+fmt(Math.max(avg(reels),avg(others)))+' views. Geef dit formaat meer ruimte in je planning.</p></article><article class="card"><b>02</b><h3>Maak deelbare momenten</h3><p>'+fmt(d.totals.shares)+' shares, of '+pct(shareRate)+' van je views. Crowdreacties, herkenning en vragen kunnen dit verder optrekken.</p></article><article class="card"><b>03</b><h3>Kopieer de winnende hook</h3><p>Je nummer 1 haalt '+fmt(top[0]?.views)+' views. Gebruik de eerste zin, onderwerp en visuele start als format, niet als kopie.</p></article>';
const tags={};top.forEach(m=>words(m.caption).forEach(t=>tags[t]=(tags[t]||0)+1));const common=Object.entries(tags).sort((a,b)=>b[1]-a[1]).slice(0,8);const avgLen=Math.round(top.reduce((s,m)=>s+(m.caption||'').length,0)/(top.length||1));$('captionSignals').innerHTML='<p><strong>Gemiddelde captionlengte top 3:</strong> '+avgLen+' tekens</p><p><strong>Hashtags in topcontent:</strong> '+(common.length?common.map(x=>'<span class="pill">'+esc(x[0])+'</span>').join(' '):'geen duidelijk patroon')+'</p><p class="muted">Dit zijn patronen uit je eigen top 3, geen garantie op extra bereik.</p>';
}catch(e){$('status').classList.add('error');$('status').querySelector('span').textContent='Datafout';$('heroTitle').textContent='Live data kon niet laden';$('heroText').textContent=e.message}}load();